dist: focal
language: ruby
script:
- ruby -e 'puts ENV["MY_ENV"] || "Hello, World!"'
deploy:
  provider: pages:git
  edge:
    branch: test_deploy
    source: DominikAlberski/dpl
  token: "$GITHUB_TOKEN"
  verbose: true
  cleanup: false
  keep_history: true
  url: github.com
  local_dir: pages/
  on:
    branch: deploy_with_custom_dpl_gem
