os: linux
dist: focal
language: ruby

env:
  - COSIGN_EXPERIMENTAL=1

services:
  - docker

keys:
  - COSIGN_PKC # must match the key identifier set in the UI

before_script:
  - echo "before script started"
  - travis_key COSIGN_KEY cosign.key  # cosign requires the key to be in a file

script:
  - echo "script started"
  - docker login -u dominikalberski841 -p "${DOCKER_HUB_PASSWORD}"
  - docker build -t dominikalberski841/hello-world .
  - docker tag dominikalberski841/hello-world:latest dominikalberski841/hello-world:0.0.1
  - docker push dominikalberski841/hello-world:0.0.1
  - echo "docker image pushed"
  # - export COSIGN_PASSWORD="${COS_PAS}"
  - cosign version
  - cosign sign --key cosign.key dominikalberski841/hello-world:0.0.1
  - cosign verify --key cosign.pub dominikalberski841/hello-world:0.0.1
  - docker logout
