language: ruby
script:
- ruby -e 'puts ENV["MY_ENV"] || "Hello, World!"'
- ruby -e 'raise "MY_ENV is not set" unless ENV["MY_ENV"]'
deploy:
  provider: pages:git
  edge: true
  token: "$GH-TOKEN"
  on:
    branch: main
notifications:
  slack:
    - rooms:
        - travis-testworkspace:jTiR7Pzm8DiIMNfuldB34Q7p
      on_success: always
      on_failure: always
    - rooms:
        - travis-testworkspace:LOKiRm5HRCiXHYQWJSzMs8Ik#build_faild_staging
      on_success: never
      on_failure: always





# - secure: "pyuRTCrWXZvfP3OlVUvEKW7hA3WXRrUtvcR2nQQ4m/a3vcgEOdb/WUvkP20hjG6QfpBFsZjAv8CYp69tLHVuwIWI/F7Yw5Axqyr3pzXa0y9x9xixH7G9qEGTxf7vrCHH59t62ii1v+Vdk7jLTK8+kkkgkbmsGxq2RfZVxg+HR8gOrsgdIwHmQ0NeyJTn69+DZehVUzd3CBuE4Y9Ko0K4fz1ghxObYqSmW2ZAKogTYdlpr+ptLUxeD01AOVDsaVRzIPLDffNqxp//V9+lGJ/QGvUFmFz7eNtpyIOuVxpdOGeRordYwJCcWnf2k3ZBZcYVa3yF+Y49YLAf2oESBIsj9oZb2x1P1cqt+8NNmYyPbdCRNLRe72mT9LyeaBq1t50rzf6LoSafWJ6xq7h3ORnib2MWchn9GwI2wiEXVsO97Wb8hkV82kDFQR1WaCCnuvAgFrbaNzayh4+wpdkuPLEeihZEqwsRDRoj3UVVq6Jn/G9pmGi0ceMnvXX/cWZgD5LQb1wiHhwOBZml3hCx/jU2HyR/+J+drKw5i4PuYSY36nsxweq7w+ZFSDoOVKW4108RV5EIG9G20RbX0oDuyfqswl2HhFg98eB8UQm+rlHffDs1yya8aGVu6AmrIkRDDcn4uf9riUuqIGTfgvTPo0FzT/zQOx0LAOe5xJEUBxBqH1I="
# - secure: cJBqO0Fbbiwoq+6pSRLdyg6IGw9uAj+ShovHhPD6BAfsj0srU8yR+nH6WOVxdoEDIxo02pH76uA1h3a0ephN2c8WNXd/KZ6Rr9uhGpisyVGFnSp4/Og3ZbrfLufuZllpZVFk6jUHhkfXOSBp5MX7vIZFLerrx0XQt02TJ75Gz7ZcTbPsI14o9vI6i+WREdKwgl297KGiSB0hXW47/Me06TLL8oosCnf7Byq+poGAKI1htUAWWCWWctqINZzpcn87ofjnrE+UBGL5jcIK5lwU9hBC837+9SWGUwK/XtcogICF4mrpI1z7UAU//gh1N998zY65gKKY9UkNNtlgiUuNra83VocA/UaBtPcwGa+29/eUDwwnAMtP+Rh+ccglU+8UdRMrMy/wBkqFbF1R33Pbs9/7qJ7iX/G4r2FtYw1oaBy/dp/xjCjzXDl8eyzZ1OOR94RdHhP1T7z33Bp2usUyZkfvCwi7vHWvZUcEu3/JUvs+qLhjZCqTtyxzeLg+cZLjy5L25WVl0bteAyic1WQ7XlnTcDSpB/YJFQFoSMBzouglFO+jJ88MdGeaJ+Sw379GXMuv3gFqj04MAO3lz+v/vRmCDmybcGEGM1VlUvoJtpH0fzCHqhoomqOlwL8EWKVRibr7diAakx5vxQtR0fYn9rsXbrhSkofTE4Gz7OfeuAs=
# template:
# - "%{repository_slug} Deployment (%{commit}) : %{message}"
# - 'Performed by: %{author}'
# - 'Build details: %{build_url}'
