os: linux
dist: xenial
rvm: 2.0.0
language: ruby
bundler_args: "--without development --deployment"
sudo: false
before_install:
- gem install bundler -v '< 2.0'
stage: test
script:
- echo "Running ruby"
- ruby -v
