language: ruby
script:
- ruby -e 'puts ENV["MY_ENV"] || "Hello, World!"'
- ruby -e 'raise "MY_ENV is not set" unless ENV["MY_ENV"]'
deploy:
  provider: pages:git
  edge: true
  token: "$GH-TOKEN"
  on:
    branch: main
notifications:
  slack:
    rooms:
    - secure: cJBqO0Fbbiwoq+6pSRLdyg6IGw9uAj+ShovHhPD6BAfsj0srU8yR+nH6WOVxdoEDIxo02pH76uA1h3a0ephN2c8WNXd/KZ6Rr9uhGpisyVGFnSp4/Og3ZbrfLufuZllpZVFk6jUHhkfXOSBp5MX7vIZFLerrx0XQt02TJ75Gz7ZcTbPsI14o9vI6i+WREdKwgl297KGiSB0hXW47/Me06TLL8oosCnf7Byq+poGAKI1htUAWWCWWctqINZzpcn87ofjnrE+UBGL5jcIK5lwU9hBC837+9SWGUwK/XtcogICF4mrpI1z7UAU//gh1N998zY65gKKY9UkNNtlgiUuNra83VocA/UaBtPcwGa+29/eUDwwnAMtP+Rh+ccglU+8UdRMrMy/wBkqFbF1R33Pbs9/7qJ7iX/G4r2FtYw1oaBy/dp/xjCjzXDl8eyzZ1OOR94RdHhP1T7z33Bp2usUyZkfvCwi7vHWvZUcEu3/JUvs+qLhjZCqTtyxzeLg+cZLjy5L25WVl0bteAyic1WQ7XlnTcDSpB/YJFQFoSMBzouglFO+jJ88MdGeaJ+Sw379GXMuv3gFqj04MAO3lz+v/vRmCDmybcGEGM1VlUvoJtpH0fzCHqhoomqOlwL8EWKVRibr7diAakx5vxQtR0fYn9rsXbrhSkofTE4Gz7OfeuAs=
      # - travis-testworkspace:jTiR7Pzm8DiIMNfuldB34Q7p#tci
    # template:
    # - "%{repository_slug} Deployment (%{commit}) : %{message}"
    # - 'Performed by: %{author}'
    # - 'Build details: %{build_url}'
