language: ruby

script:
- ruby -e 'puts ENV["MY_ENV"] || "Hello, World!"'
- ruby script.rb

jobs:
  include:
    - stage: test
      script:
        - echo "Running stage tests"
    - stage: test
      script:
        - echo "Running failing tests"
        - echo "going to sleep for 5 seconds"
        - ruby -e 'sleep 5'
        - echo "done sleeping"
        - ruby -e 'raise "Fail"'
    - stage: foo
      script:
        - echo "Running foo stage"
        - echo "going to sleep for 10 seconds"
        - ruby -e 'sleep 10'
        - echo "done sleeping in foo stage"
    - stage: deploy
      script:
        - echo "this should not run"
    - stage: deploy
      script:
        - echo "this should not run"
