language: ruby

before_install:
# - openssl aes-256-cbc -K $encrypted_4b6fcb2d521e_key -iv $encrypted_4b6fcb2d521e_iv
#   -in test.txt.enc -out test.txt -d
# - cat test.txt
script:
- ruby -e 'puts ENV["MY_ENV"] || "Hello, World!"'
# - cat test.txt
# jobs:
#   include:
#     - os: osx
#       osx_image: xcode14.2
#       rvm:
#         - "3.2"
