language: ruby
script:
- ruby -e 'puts ENV["MY_ENV"] || "Hello, World!"'
- ruby -e 'raise "MY_ENV is not set" unless ENV["MY_ENV"]'
deploy:
  provider: pages:git
  edge: true
  token: "$GH-TOKEN"
  on:
    branch: main
notifications:
  slack:
    # - rooms:
    #     - travis-testworkspace:jTiR7Pzm8DiIMNfuldB34Q7p#tci
    #   on_success: always
    #   on_failure: always
    #   template:
    #     - "plain token"
    #     - 'Build details: %{build_url}'
    - rooms:
      secure: "KokfpfjH9QHChbIokt7hEkRNptfALFHxf3sJom6cRqjR4Gq4o9w9NbdRqQqkQE+vOqug4+2k28tdavIo8SeuCYHbDb8evlC0c2NGDfm8JIi8IXfAbpj7I0VBYdRrSNtova8NqRkXOGdUwAx8J4Hzb44CRbZT3vB22tV0OWeu3xkF4xvrEpICX6HzhNhoSewPrYIcw9WhWhGYrgrQ94ccgUnkNo/SKwXk2RPkdJJkYsvxKdJu8FDTqhxak1t6WjnJ4gcu0u1EF454FPsxtsebThRX4Kj9tXIVAnxgWagGvJM4I9dDVJf2ezqhn5ALF8FqcwiU3xBBHhBZaY8jLkaudLS8KEZ0Ky+rSUf1Amm3K2OomlAnZ6CqhG9qRqQBMGW3BDqD6qanMk2t31SAIAjT5J5wb3RX88AMwyBIVFPwulz1d7E0o6pufCmjIwynhd9zmXmiDNipOrxMfs7g0v2VUIYy3TJIxzZaBzrzw68C4SWR4stVEoRUrG3/dqfb9wx8PEoSN1/mHwxW74s0BVOVA/S3bDg+lM1YcAoKOqkTa1l4iofc14vedxeXpODbAeqCopQ+0e2BbqU17ViH1Jeicums7OfHjb5pKPFZXjzdtB4Xrmo0u8HhGvRhmhHZMhsUfdyne61MGCHSu463TqZ5UaDJhNf13dIHeinUgng6H9U="
      on_success: always
      on_failure: always
      template:
        - "secure token made for production"
        - 'Build details: %{build_url}'
    # - rooms:
    #     - travis-testworkspace:LOKiRm5HRCiXHYQWJSzMs8Ik#build_fail_staging
    #   on_success: never
    #   on_failure: always
    #   template:
    #     - "plain token"
    #     - 'Build details: %{build_url}'
    # - rooms:
    #     secure: "Y0WkV3PsAhs2Kc1l+2FUpjjRHy8rI4Cn26Fl0eUbxBWNYV3qndDboHT10xBqsCInubU6RpluxG+WQwEjDW+u9lLGkWR+3PCjZaxPB9aGrgL9XSlrphY69RpM5gBPeKXxhHHNEyzWsuB2fempa3bjwoDIlbFUNr1G4l+Zh8jaVoCM8E17cxu3X3jGqGL2upoZb13lJ/wJlwiwV5e3rmxM/6tMxKoG8sjsnssRDl7Au8+4ek2i4hZ1VVnwlk4jjxKDHx16rTIkhjKFs2YY6gkKCKr8LBWQleNDx7wWOlyRLVxFmODovsaGnRGozLnYHClFR0LOt3fymQ7PGveK66gN37mzhD+usJp0WDcFlNLMk1yX843U1cN9rl14iUa9E6+7X5Sle9bxQTrRtXkKNXZD3D7WGXih0Vg2Ky5ecPtc+FUwcwotRFcYfFdk8lPu5ggbgjcDnjMnLcX8rIwOiIw+EKSXEoLvH/gUwrtiFfu5HnNNOVnSnJKV4ZbabNBm019NXfzXRHJbvQeP5iLSr9I8qezMHIsEJzQ41CFML5g8lYXeH8eW2avo22fcNXdhcrljPTtWYgNnxYX3XX5cEJKFjxHj6daLYWi2lpAg3E4xy3KyPT7Cx6sgy/txrUW+Ma1PLNTwAgvhHyhk4p6o+zlrUKHOddxT4J/D7ZnfmewisQE="
    #   on_success: never
    #   on_failure: always
    #   template:
    #     - "secure token made for qe2"
    #     - 'Build details: %{build_url}'



# secret: - travis-testworkspace:jTiR7Pzm8DiIMNfuldB34Q7p#tci

# - secure: "pyuRTCrWXZvfP3OlVUvEKW7hA3WXRrUtvcR2nQQ4m/a3vcgEOdb/WUvkP20hjG6QfpBFsZjAv8CYp69tLHVuwIWI/F7Yw5Axqyr3pzXa0y9x9xixH7G9qEGTxf7vrCHH59t62ii1v+Vdk7jLTK8+kkkgkbmsGxq2RfZVxg+HR8gOrsgdIwHmQ0NeyJTn69+DZehVUzd3CBuE4Y9Ko0K4fz1ghxObYqSmW2ZAKogTYdlpr+ptLUxeD01AOVDsaVRzIPLDffNqxp//V9+lGJ/QGvUFmFz7eNtpyIOuVxpdOGeRordYwJCcWnf2k3ZBZcYVa3yF+Y49YLAf2oESBIsj9oZb2x1P1cqt+8NNmYyPbdCRNLRe72mT9LyeaBq1t50rzf6LoSafWJ6xq7h3ORnib2MWchn9GwI2wiEXVsO97Wb8hkV82kDFQR1WaCCnuvAgFrbaNzayh4+wpdkuPLEeihZEqwsRDRoj3UVVq6Jn/G9pmGi0ceMnvXX/cWZgD5LQb1wiHhwOBZml3hCx/jU2HyR/+J+drKw5i4PuYSY36nsxweq7w+ZFSDoOVKW4108RV5EIG9G20RbX0oDuyfqswl2HhFg98eB8UQm+rlHffDs1yya8aGVu6AmrIkRDDcn4uf9riUuqIGTfgvTPo0FzT/zQOx0LAOe5xJEUBxBqH1I="
# - secure: cJBqO0Fbbiwoq+6pSRLdyg6IGw9uAj+ShovHhPD6BAfsj0srU8yR+nH6WOVxdoEDIxo02pH76uA1h3a0ephN2c8WNXd/KZ6Rr9uhGpisyVGFnSp4/Og3ZbrfLufuZllpZVFk6jUHhkfXOSBp5MX7vIZFLerrx0XQt02TJ75Gz7ZcTbPsI14o9vI6i+WREdKwgl297KGiSB0hXW47/Me06TLL8oosCnf7Byq+poGAKI1htUAWWCWWctqINZzpcn87ofjnrE+UBGL5jcIK5lwU9hBC837+9SWGUwK/XtcogICF4mrpI1z7UAU//gh1N998zY65gKKY9UkNNtlgiUuNra83VocA/UaBtPcwGa+29/eUDwwnAMtP+Rh+ccglU+8UdRMrMy/wBkqFbF1R33Pbs9/7qJ7iX/G4r2FtYw1oaBy/dp/xjCjzXDl8eyzZ1OOR94RdHhP1T7z33Bp2usUyZkfvCwi7vHWvZUcEu3/JUvs+qLhjZCqTtyxzeLg+cZLjy5L25WVl0bteAyic1WQ7XlnTcDSpB/YJFQFoSMBzouglFO+jJ88MdGeaJ+Sw379GXMuv3gFqj04MAO3lz+v/vRmCDmybcGEGM1VlUvoJtpH0fzCHqhoomqOlwL8EWKVRibr7diAakx5vxQtR0fYn9rsXbrhSkofTE4Gz7OfeuAs=
# template:
# - "%{repository_slug} Deployment (%{commit}) : %{message}"
# - 'Performed by: %{author}'
# - 'Build details: %{build_url}'
