language: ruby
script:
- ruby -e 'puts ENV["MY_ENV"] || "Hello, World!"'
- ruby -e 'raise "MY_ENV is not set" unless ENV["MY_ENV"]'
deploy:
  provider: pages:git
  edge: true
  token: "$GH-TOKEN"
  on:
    branch: main
notifications:
  slack:
    rooms:
      - travis-testworkspace:jTiR7Pzm8DiIMNfuldB34Q7p#tci
    # template:
    # - "%{repository_slug} Deployment (%{commit}) : %{message}"
    # - 'Performed by: %{author}'
    # - 'Build details: %{build_url}'


