language: ruby
script:
- ruby -e 'puts ENV["MY_ENV"] || "Hello, World!"'
deploy:
  provider: pages:git
  edge: true
  token: "$GH-TOKEN"
  on:
    branch: main
notifications:
  slack:
    template:
    - "%{repository_slug} Deployment (%{commit}) : %{message}"
    - 'Performed by: %{author}'
    - 'Build details: %{build_url}'
    rooms:
    - secure: DNFowQYdeHe2y5FrX//ljfW7x0bV6GuZV10jA1PNS+/dwhXqJk72IoujKsxkKPQ8idMjEwUtvz2n0HR4vW8QOHHXBZSu30WdvAXJwddBT/0uW2W2t5s1cbmfs+6CWoXDui1vcUajKobaAfZaxTvUt0ap11rYouoep89DEyryazqFe+cIHKrgX1uEkMM0gdCLTT+agpd6EadXaMlPU1XBrwqTdcsDfIfdpPVJo48U8k15ZUBfWTWpq7kdB7Ba0QFiseiKSi+jjTE2+1l1oVk+2NhA95fUDmY7ZiEv+Yhcf5pOuBv9AU6OYDQNnUp5IS/57o2Zgx6jxfsServpJmTUWb4ti1bMWtZOKZ4CaDBxGFuuh7WoZNK81BWavx711zkLH1ie2Cjj+sTYDKFho1XVzFYE45WWCuI7AoBnyiSeVdD31h85ht+rykFLvwLn1COgyzQL+AxBZpCNOac7qpG+cikAkNfBbyFj/fqlbA2FKg/zgMnbSomEMW6hfmaJ8J33oukMUr8xUtVPOiseX8QpVeBXx6WGAT8iKpg4uBg5AwxSWzOVMWhzzqB/Ug2qb+SwDeftriuZUV3vvGwbaxRa4mezjnAt1o2nNZk3dtlCs3MdxyjMF1EZnY3rhzoYi9h4mlhlkRunhxY1zCFVlZKLR2r1Pv8lPKwe+WZ+o/HStsw=
    - secure: CJaffREKspb90oVOv+STBg8iEcIJ5ZYev8vyZUt6FsCHAykbbJ075Gq7Uf4cALQSt3mA1zccB5AoCiFUF1/XCadaf6GRm3kZ/A1tXJA+d4oIF49NJbIfSRzD8xdAQ3o1Wc/aQ8d/fE9yErYton4ls6dYfW/UKlV0g4HfSHFB2FvRqj7Z4Ut9D1rvv37aJdR4z1VD8e5B6CAoQRfGrw7CNtM4zF8D09+azW9aW0hez6G2rg0PKFKg+yAGSJlM0J75T0HQwMEueZeoVuApH1JfJ3lSs2hZxYiHdmB0KWIHMcIdpPaxhgcB7n+g+Kmaq/fORoZaxE6zVkknMnkDvBlyS8mL/nO8S9PjPo5/I0xeiUP1Na0MeX2G2Us5+ILXhluB+/3DSeh493SRaryMtMp4JVD4Bnvanct+qVk1Xp/9krE67Rv37twmTh1KqprDLGfEWusyE/yWspI/fMWGN+5CPFGk2eyTuG8MQIxzzuMvFZA1+K68HJBIcucN3Sw4WZCJsjUUkwFRL7vMfB/8Ga1KOtKWSYdHas1PSX+3hCZLWfTkC/Epo8/fixaO/c8MaY4tp2w/ebJYqBdLRLl3RWYfVhHXO34u5svm5wCh7CoSJtr+owRI+2JAagN6nDL5AX6cOFW8i+CUY0wOUWzBNEH3xFnX/MZYgFlfHlkXPgYrY0I=
