os: linux
language: ruby
dist: jammy
install: skip
script: true
deploy:
  provider: packagecloud
  username: usernamehere
  repository: repohere
  token: "$PACKAGECLOUD_TOKEN"
  edge:
    branch: v.2.0.6.beta.1
  on:
    all_branches: true

