os: linux
dist: focal
language: ruby

env:
  - COSIGN_EXPERIMENTAL=1
services:
  - docker

keys:
  - COSSIGN # must match the key identifier set in the UI

before_script:
  - travis_key COSSIGN cosign.key  # cosign requires the key to be in a file

script:
  - docker login -u dominikalberski841 -p "${DOCKER_HUB_PASSWORD}"
  - docker build -t dominikalberski841/hello-world .
  - docker tag hello-world dominikalberski841/hello-world
  - docker push dominikalberski841/hello-world
  - cosign sign --key cosign.key dominikalberski841/hello-world
  - cosign verify --key cosign.pub dominikalberski841/hello-world
  - docker logout
