dist: focal
language: ruby
script:
- ruby -e 'puts ENV["MY_ENV"] || "Hello, World!"'
# before_deploy:
  # - rvm use 2.7.6 --default
  # - echo "travis_internal_ruby is $(travis_internal_ruby)"
  # - rvm list

deploy:
  # dpl_version: 2.0.5.2.beta.1
  # edge: true
  edge:
    branch: v2.0.5.3.beta.1
  provider: releases
  name: $TRAVIS_TAG
  token: $GITHUB_TOKEN
  tag_name: $TRAVIS_TAG
  cleanup: false
  overwrite: true
  file_glob: true
  file: /home/travis/build/result/*
  on:
    tags: true
